[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Single Page Application fallback (React Router support)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
